build:
  stage: test
  image: alpine:edge
  before_script:
    - apk add --no-cache build-base meson samurai tiff-dev linux-headers scdoc
  script:
    - meson build --buildtype release --werror
    - ninja -C build
    - cd build && meson test --no-rebuild

docs:
  stage: test
  image: alpine:edge
  before_script:
    - apk add --no-cache python3 py3-sphinx make
  script:
    - cd docs
    - make html

pages:
  stage: deploy
  image: alpine:edge
  before_script:
    - apk add --no-cache python3 py3-sphinx make
  script:
    - cd docs
    - make html
  artifacts:
    paths:
      - docs/_build/html
  environment: production